
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team02-f23-5pm-4
owner: ucsb-cs156-f23
repo_name: team02-f23-5pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjU5MjUwODA=","is_bot":false,"login":"ajs808","name":"Arul Saxena"},"headRefName":"Arul-DiningMenuController","number":48,"title":"Create UCSBDiningCommonsMenuItemController, add GET (index) and POST (create)","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-4/pull/48"},{"author":{"id":"MDQ6VXNlcjY0Mjg2NjM1","is_bot":false,"login":"katytsao","name":"Katy Tsao"},"headRefName":"Katy-Articles","number":47,"title":"Create Articles database table","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-4/pull/47"},{"author":{"id":"MDQ6VXNlcjQ2Njk2NDkw","is_bot":false,"login":"mitali-g","name":"Mitali Gaidhani"},"headRefName":"Mitali-MenuItemReview","number":46,"title":"Added database table for MenuItemReview","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-4/pull/46"}]
