
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team02-f23-5pm-4
owner: ucsb-cs156-f23
repo_name: team02-f23-5pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjI1NTMzNjIw","is_bot":false,"login":"Francisc0Leyva","name":"Francisco Justin Leyva"},"headRefName":"Justin-HelpRequests","number":72,"title":"add DELETE endpoint","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-4/pull/72"},{"author":{"id":"U_kgDOBXdYPQ","is_bot":false,"login":"aditiphatak","name":"Aditi Phatak"},"headRefName":"Aditi-RecommendationRequestDelete","number":71,"title":"Added DELETE endpoint for RecommendationRequest database","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-4/pull/71"},{"author":{"id":"U_kgDOBXdYPQ","is_bot":false,"login":"aditiphatak","name":"Aditi Phatak"},"headRefName":"Aditi-RecommendationRequestPut","number":70,"title":"Add PUT (edit) endpoint for a single record in RecommendationRequest database","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-4/pull/70"},{"author":{"id":"MDQ6VXNlcjU0Mjg0MTQ4","is_bot":false,"login":"kendrick-lee","name":""},"headRefName":"Kendrick-UCSBOrganizationControllerDelete","number":69,"title":"Added UCSBOrganizationController Delete & Tests","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-4/pull/69"},{"author":{"id":"MDQ6VXNlcjU0Mjg0MTQ4","is_bot":false,"login":"kendrick-lee","name":""},"headRefName":"Kendrick-UCSBOrganizationControllerPut","number":68,"title":"Added UCSBOrganizationController Put & Tests","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-4/pull/68"},{"author":{"id":"U_kgDOBXdYPQ","is_bot":false,"login":"aditiphatak","name":"Aditi Phatak"},"headRefName":"Aditi-RecommendationRequestShow","number":67,"title":"Add GET (show) endpoint for single record in RecommendationRequest Database Table","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-4/pull/67"},{"author":{"id":"MDQ6VXNlcjU0Mjg0MTQ4","is_bot":false,"login":"kendrick-lee","name":""},"headRefName":"Kendrick-UCSBOrganizationControllerGet","number":66,"title":"Added UCSBOrganizationController Get & Tests","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-4/pull/66"}]
