
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team02-f23-5pm-4
owner: ucsb-cs156-f23
repo_name: team02-f23-5pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjU0Mjg0MTQ4","is_bot":false,"login":"kendrick-lee","name":""},"headRefName":"Kendrick-UCSBOrganization","number":45,"title":"Added Database Table for UCSB Organization","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-4/pull/45"},{"author":{"id":"MDQ6VXNlcjI1NTMzNjIw","is_bot":false,"login":"Francisc0Leyva","name":"Francisco Justin Leyva"},"headRefName":"Justin-HelpRequests","number":44,"title":"HelpRequest Entity and Repository","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-4/pull/44"}]
